"""Tests for issue #29 (A4): domain-specific entity types generated by the
ontology were discarded for archetype-based (sentiment campaign) simulations.

`SimulationConfigGenerator.generate_config()` is called with `entities=[]`
whenever a campaign uses the preset archetype library instead of Zep graph
entities. With nothing to match a generated initial-post `poster_type`
against, *every* initial post fell back to "the agent with the highest
influence" regardless of what type the LLM picked. These tests cover the
`poster_agent_pool` override that fixes this: the event-config LLM prompt
should only offer real archetype types, and `_assign_initial_post_agents`
should match against the real archetype pool instead of an empty list.
"""

from app.config import Config
from app.services.simulation_config_generator import AgentActivityConfig, SimulationConfigGenerator
from app.services.simulation_manager import SimulationManager


def _make_generator(monkeypatch):
    monkeypatch.setattr(Config, "LLM_API_KEY", "test-llm-key")
    return SimulationConfigGenerator()


def _pool():
    return [
        AgentActivityConfig(
            agent_id=1, entity_uuid="a1", entity_name="skeptic_01", entity_type="skeptic",
            influence_weight=0.4,
        ),
        AgentActivityConfig(
            agent_id=2, entity_uuid="a2", entity_name="early_adopter_02", entity_type="early_adopter",
            influence_weight=0.9,
        ),
    ]


def test_generate_event_config_offers_only_archetype_types_when_pool_given(testing_env, monkeypatch):
    generator = _make_generator(monkeypatch)
    captured = {}

    def fake_llm(prompt, system_prompt):
        captured["prompt"] = prompt
        return {"hot_topics": [], "narrative_direction": "", "initial_posts": [], "reasoning": "ok"}

    monkeypatch.setattr(generator, "_call_llm_with_retry", fake_llm)

    generator._generate_event_config(
        context="ctx", simulation_requirement="req", entities=[], poster_agent_pool=_pool()
    )

    prompt = captured["prompt"]
    assert "skeptic" in prompt
    assert "early_adopter" in prompt
    # The entity-graph-flow example types must not leak into an archetype run.
    assert "Official/University" not in prompt


def test_generate_event_config_falls_back_to_entities_when_no_pool(testing_env, monkeypatch):
    generator = _make_generator(monkeypatch)
    captured = {}

    def fake_llm(prompt, system_prompt):
        captured["prompt"] = prompt
        return {"hot_topics": [], "narrative_direction": "", "initial_posts": [], "reasoning": "ok"}

    monkeypatch.setattr(generator, "_call_llm_with_retry", fake_llm)

    generator._generate_event_config(context="ctx", simulation_requirement="req", entities=[])

    assert "Official/University" in captured["prompt"]


def test_assign_initial_post_agents_matches_archetype_pool(testing_env, monkeypatch):
    generator = _make_generator(monkeypatch)
    pool = _pool()

    from app.services.simulation_config_generator import EventConfig

    event_config = EventConfig(
        initial_posts=[{"content": "Not sure this is worth it.", "poster_type": "skeptic"}],
        scheduled_events=[], hot_topics=[], narrative_direction="",
    )

    result = generator._assign_initial_post_agents(event_config, pool)

    assert result.initial_posts[0]["poster_agent_id"] == 1  # the skeptic, not the fallback highest-influence agent


def test_assign_initial_post_agents_falls_back_only_on_genuine_mismatch(testing_env, monkeypatch):
    generator = _make_generator(monkeypatch)
    pool = _pool()

    from app.services.simulation_config_generator import EventConfig

    event_config = EventConfig(
        initial_posts=[{"content": "x", "poster_type": "totally_unknown_type"}],
        scheduled_events=[], hot_topics=[], narrative_direction="",
    )

    result = generator._assign_initial_post_agents(event_config, pool)

    # No archetype named "totally_unknown_type" exists in the pool -> falls
    # back to the highest-influence agent (agent_id=2), same as before.
    assert result.initial_posts[0]["poster_agent_id"] == 2


def test_build_archetype_agent_configs_produces_matching_pool():
    archetype_map = [
        {"agent_id": 1, "archetype": "skeptic", "username": "skeptic_01"},
        {"agent_id": 2, "archetype": "early_adopter", "username": "early_adopter_02"},
    ]

    configs = SimulationManager._build_archetype_agent_configs(archetype_map)

    assert [c.entity_type for c in configs] == ["skeptic", "early_adopter"]
    assert [c.agent_id for c in configs] == [1, 2]
    assert all(isinstance(c, AgentActivityConfig) for c in configs)
